services:
  app:
    build: ./
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      PG_DSN: postgres://postgres:password@db:5432/shop?sslmode=disable
      TOKEN_SECRET_KEY: "01234567890123456789012345678901"
    networks:
      - mynetwork


  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - 5432:5432
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./internal/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/data:rw
    ports:
      - "9090:9090"
    networks:
      - mynetwork

networks:
  mynetwork: