services:
  app:
    build: ./
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop
      - TOKEN_SECRET_KEY="01234567890123456789012345678901"

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - 5432:5432
